spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
          google:
            clientId: google-client-id
            clientSecret: google-client-secret
server:
  port: 9090
